### ISSUE TITLE
Ignoring Exception is On_Message

### ISSUE THREAD

**Issue by Allread** [ScottJDaley/ada#78]
Hello,
I just hosted ADA on my server by following the prerequisites.
I intend to make a French version :)

But when I ask ADA, the console gives me an error message.

Cordially

![image](https://user-images.githubusercontent.com/16807391/129566582-73140b2d-b0e1-4a4b-b202-2a8df225c3c5.png)

**Comment by ScottJDaley** [comment]
Is this issue fixed with your PRs? I can definitely see how there would be issues if the wiki url changed. Looks like this particular error is because it fails to find a picture for iron ore on the wiki.

This project could really use some better error handling in general, but I don't currently have the time to improve it.

**Comment by ScottJDaley** [comment]
I believe this is fixed as of https://github.com/ScottJDaley/ada/commit/59c12e06262777d3e3d407a603a9c3154042a86a.
